### ISSUE TITLE
Business Profile Phone Numbers Field

### ISSUE THREAD

**Issue by malexander15** [TampaDevs/talent.tampa.dev#37]
### Personas

As an administrator, I want to have accurate contact information on file for business customers. This makes sure I'm able to reach out to them by phone if needed. 

### Platform Outcomes

Engagement:
- Keep records of Business phone numbers.

Growth:
- Improve customer support for businesses

#### Platform Features
- [x] A new field is added to the create and edit business information form

#### Business Features
- [x] New businesses must provide a phone number
- [x] Existing businesses can update their profile to include a phone number

#### Implementation
- [x] Update [Business model](https://github.com/TampaDevs/talent.tampa.dev/blob/main/app/models/business.rb) with new attribute for phone numbers.
- [x] Update [Business Controller](https://github.com/TampaDevs/talent.tampa.dev/blob/main/app/controllers/businesses_controller.rb) for create/update
- [x] Create Migration to add a column for phone numbers on the business table
- [x] Add/Update tests for Business model

#### Task notes
- Model should include validation/normalization on the phone number field
- Use a helper or concern to format the phone number as such:
5551234567 ----> (555) 123-4567

**Comment by chtzvt** [comment]
Closed as completed. This feature has shipped, great work!

**Comment by chtzvt** [comment]
@malexander15 Let's also show this phone number on an Admin's view of the Business' profile page, as well.

**Comment by chtzvt** [comment]
Per my last comment, the updated UI is shipping.
